### ISSUE TITLE
app doesnt find network when switching from wi-fi to 4g 

### ISSUE THREAD

**Issue by Alusar** [GuardianLabs/guardian-keyper#25]
steps:
1. open app (wi-fi connected)
2. create a vault
3. turn off wi-fi,  4g connection is on
4. scan guardian QR-code 

actual result: 
as guardian, doesnt get incoming request
as owner, to send a request after changing network, need to restart app

expected result:
as guardian, receives incoming request
as owner, no reboot required when changing network type

**Comment by alexandrim0** [comment]
fixed in 2.1.3
wont work on Android < 8
